# Generated by Django 3.2.20 on 2023-07-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titlte',
            new_name='title',
        ),
    ]
