# Generated by Django 3.2.20 on 2023-07-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_titlte_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contents',
            new_name='content',
        ),
    ]
